#!/usr/bin/env python

import sys
import os
import pythunder


path = os.path.abspath(os.path.dirname(pythunder.__file__))
placer_binary = os.path.join(path, "partition")
os.system(" ".join([placer_binary] + sys.argv[1:]))

