#!/usr/bin/env python

import sys
import os
import pycyclone
import subprocess


path = os.path.abspath(os.path.dirname(pycyclone.__file__))
router_binary = os.path.join(path, "router")
subprocess.call([router_binary] + sys.argv[1:])

