#!/usr/bin/env python

import sys
import os
import pycyclone


path = os.path.abspath(os.path.dirname(pycyclone.__file__))
placer_binary = os.path.join(path, "router")
os.system(" ".join([placer_binary] + sys.argv[1:]))

