name: MacOS Wheel Test

on: [push]

jobs:
  build:

    runs-on: macos-10.15
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Setup Python environment 🐍
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install igraph
      shell: bash
      run: |
          brew install igraph
    - name: Install Python packages
      shell: bash
      run: |
          pip install wheel pytest
    - name: Build and run wheel
      shell: bash
      env:
        OS: osx
        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        # miniconda uses 10.9
        MACOSX_DEPLOYMENT_TARGET: 10.9
        KRATOS_DEBUG: 1
      run: |
        source ./scripts/ci.sh
    - uses: actions/upload-artifact@v1
      with:
        name: py3.7 wheel
        path: dist/
